const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getScreenInfo: () => ipcRenderer.invoke('get-screen-info'),
  getPetMode: () => ipcRenderer.invoke('get-pet-mode'),
  setIgnoreMouseEvents: (ignore) => ipcRenderer.send('set-ignore-mouse-events', ignore),
  flashTray: () => ipcRenderer.send('flash-tray'),
  quitApp: () => ipcRenderer.send('quit-app'),
  saveDiary: (entry) => ipcRenderer.send('save-diary', entry),
  loadDiary: () => ipcRenderer.invoke('load-diary'),
  setWindowSize: (size) => ipcRenderer.invoke('set-window-size', size),
  setWindowSizeCustom: (x, y, w, h) => ipcRenderer.invoke('set-window-size-custom', x, y, w, h),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setAutoLaunch: (enabled) => ipcRenderer.send('set-auto-launch', enabled),
  showSettings: () => ipcRenderer.send('show-settings'),
  closeSettings: () => ipcRenderer.send('close-settings'),
  startDraw: () => ipcRenderer.send('start-draw'),
  drawConfirm: (x, y, w, h) => ipcRenderer.send('draw-confirm', x, y, w, h),
  drawCancel: () => ipcRenderer.send('draw-cancel'),
  onSwitchMode: (callback) => ipcRenderer.on('switch-mode', (_, mode) => callback(mode)),
  onFullscreenDetected: (callback) => ipcRenderer.on('fullscreen-detected', (_, fs) => callback(fs)),
  onShowStatus: (callback) => ipcRenderer.on('show-status', () => callback()),
  onShowDiary: (callback) => ipcRenderer.on('show-diary', () => callback()),
  onShowGifManager: (callback) => ipcRenderer.on('show-gif-manager', () => callback()),
  onShowSettings: (callback) => ipcRenderer.on('show-settings', () => callback()),
  onToggleMute: (callback) => ipcRenderer.on('toggle-mute', (_, muted) => callback(muted)),
  onToggleFocus: (callback) => ipcRenderer.on('toggle-focus', (_, focused) => callback(focused)),
  onPassthroughChanged: (callback) => ipcRenderer.on('passthrough-changed', (_, enabled) => callback(enabled)),
  setPassthrough: (enabled) => ipcRenderer.send('set-passthrough', enabled),
  onDrawResult: (callback) => ipcRenderer.on('draw-result', (_, x, y, w, h) => callback(x, y, w, h)),
  onWindowResized: (callback) => ipcRenderer.on('window-resized', (_, bounds) => callback(bounds)),
  openGifStatePanel: () => ipcRenderer.send('open-gif-state-panel'),
  onShowGifStatePanel: (callback) => ipcRenderer.on('show-gif-state-panel', () => callback()),
  expandWindowForPanel: () => ipcRenderer.send('expand-window-for-panel'),
  restoreWindowAfterPanel: () => ipcRenderer.send('restore-window-after-panel')
});
